image: marcoturi/ionic:latest

before_script:
  - yarn config set cache-folder yarn-cache
  - yarn
  - export DISPLAY=:99

cache:
  paths:
    - yarn-cache/

test:
  script:
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
    - yarn run test
    - yarn run build
    - yarn run start_e2e
    - yarn run e2e